name: Publish
on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install hatch
        run: |
          pip install --upgrade pip
          pip install hatch
      - name: Build
        run: hatch build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
